<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kk_timeline"
 *
 * Auto generated by Extension Builder 2017-08-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'KK Timeline',
    'description' => 'Timeline',
    'category' => 'plugin',
    'author' => 'Thomas Kemendi',
    'author_email' => 'kemendi@kreativ-konzept.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-10.4.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
